name: foldable_sidebar
description: An easy to use Package for adding Foldable Flutter Navigation Sidebar to your Flutter Application. Now with null safety
version: 2.0.0
homepage: https://github.com/openWebX/foldable_sidebar.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
